version: "3.4"

services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead

  adminer:
    image: adminer:4
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:8080"

  composer:
    image: composer:2
    command: composer install
    depends_on:
      - php
    volumes: 
      - ./:/app

  php:
    image: php:8.0-fpm-alpine
    build: .docker/images/php/
    working_dir: /home/app
    depends_on:
      - mysql
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./:/home/app
      - .docker/conf/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:1.15-alpine
    # build: .docker/images/nginx/
    working_dir: /home/app
    depends_on:
      - php
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./:/home/app
      - .docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
